# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'list_kuih_raya.ui'
##
## Created by: Qt User Interface Compiler version 6.6.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QFrame, QLabel, QMainWindow,
    QMenu, QMenuBar, QSizePolicy, QStatusBar,
    QTabWidget, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(400, 550)
        self.actionnew_customer = QAction(MainWindow)
        self.actionnew_customer.setObjectName(u"actionnew_customer")
        self.actionnew_customer.setCheckable(False)
        self.actionnew_customer.setChecked(False)
        self.actionnew_customer.setShortcutContext(Qt.ApplicationShortcut)
        self.actionnew_customer.setAutoRepeat(False)
        self.actionnew_customer.setMenuRole(QAction.ApplicationSpecificRole)
        self.actionnew_customer.setShortcutVisibleInContextMenu(False)
        self.actionexisting_customer = QAction(MainWindow)
        self.actionexisting_customer.setObjectName(u"actionexisting_customer")
        self.actionlist_kuih_raya = QAction(MainWindow)
        self.actionlist_kuih_raya.setObjectName(u"actionlist_kuih_raya")
        self.actionlist_kuih_raya.setCheckable(False)
        self.actionlist_kuih_raya.setChecked(False)
        self.actionlist_kuih_raya.setEnabled(True)
        self.actionnew_order = QAction(MainWindow)
        self.actionnew_order.setObjectName(u"actionnew_order")
        self.actionupdate_order = QAction(MainWindow)
        self.actionupdate_order.setObjectName(u"actionupdate_order")
        self.actionpreview_order = QAction(MainWindow)
        self.actionpreview_order.setObjectName(u"actionpreview_order")
        self.actionpreview_stocks = QAction(MainWindow)
        self.actionpreview_stocks.setObjectName(u"actionpreview_stocks")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.label = QLabel(self.centralwidget)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(120, 10, 161, 51))
        font = QFont()
        font.setFamilies([u"Lucida Handwriting"])
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setAlignment(Qt.AlignCenter)
        self.label.setWordWrap(False)
        self.label_2 = QLabel(self.centralwidget)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(120, 60, 141, 16))
        font1 = QFont()
        font1.setFamilies([u"Georgia"])
        font1.setPointSize(9)
        font1.setItalic(True)
        self.label_2.setFont(font1)
        self.label_2.setAlignment(Qt.AlignCenter)
        self.tabWidget = QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(u"tabWidget")
        self.tabWidget.setEnabled(True)
        self.tabWidget.setGeometry(QRect(20, 90, 361, 401))
        font2 = QFont()
        font2.setFamilies([u"Georgia"])
        font2.setPointSize(7)
        self.tabWidget.setFont(font2)
        self.tabWidget.setTabBarAutoHide(False)
        self.tab_1 = QWidget()
        self.tab_1.setObjectName(u"tab_1")
        self.label_7 = QLabel(self.tab_1)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(100, 20, 141, 16))
        font3 = QFont()
        font3.setFamilies([u"Georgia"])
        font3.setPointSize(9)
        font3.setBold(False)
        font3.setItalic(False)
        self.label_7.setFont(font3)
        self.label_7.setAlignment(Qt.AlignCenter)
        self.frame_2 = QFrame(self.tab_1)
        self.frame_2.setObjectName(u"frame_2")
        self.frame_2.setGeometry(QRect(80, 50, 191, 171))
        self.frame_2.setContextMenuPolicy(Qt.NoContextMenu)
        self.frame_2.setFrameShape(QFrame.Box)
        self.frame_2.setFrameShadow(QFrame.Raised)
        self.frame_2.setLineWidth(2)
        self.label_8 = QLabel(self.frame_2)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(10, 10, 171, 151))
        self.label_8.setPixmap(QPixmap(u"../KuihRaya/almond_london.png"))
        self.label_8.setScaledContents(True)
        self.label_9 = QLabel(self.tab_1)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(20, 230, 311, 81))
        self.label_9.setFont(font3)
        self.label_9.setAlignment(Qt.AlignCenter)
        self.label_9.setWordWrap(True)
        self.label_10 = QLabel(self.tab_1)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(60, 310, 221, 51))
        font4 = QFont()
        font4.setFamilies([u"Georgia"])
        font4.setPointSize(9)
        font4.setBold(True)
        font4.setItalic(False)
        self.label_10.setFont(font4)
        self.label_10.setAlignment(Qt.AlignCenter)
        self.tabWidget.addTab(self.tab_1, "")
        self.tab_2 = QWidget()
        self.tab_2.setObjectName(u"tab_2")
        self.label_11 = QLabel(self.tab_2)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(60, 310, 221, 51))
        self.label_11.setFont(font4)
        self.label_11.setAlignment(Qt.AlignCenter)
        self.label_12 = QLabel(self.tab_2)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(20, 230, 311, 81))
        self.label_12.setFont(font3)
        self.label_12.setAlignment(Qt.AlignCenter)
        self.label_12.setWordWrap(True)
        self.label_13 = QLabel(self.tab_2)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(100, 20, 141, 16))
        self.label_13.setFont(font3)
        self.label_13.setAlignment(Qt.AlignCenter)
        self.frame_3 = QFrame(self.tab_2)
        self.frame_3.setObjectName(u"frame_3")
        self.frame_3.setGeometry(QRect(80, 50, 191, 171))
        self.frame_3.setContextMenuPolicy(Qt.NoContextMenu)
        self.frame_3.setFrameShape(QFrame.Box)
        self.frame_3.setFrameShadow(QFrame.Raised)
        self.frame_3.setLineWidth(2)
        self.label_14 = QLabel(self.frame_3)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(10, 10, 171, 151))
        self.label_14.setPixmap(QPixmap(u"../KuihRaya/cookies.jpeg"))
        self.label_14.setScaledContents(True)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QWidget()
        self.tab_3.setObjectName(u"tab_3")
        self.label_15 = QLabel(self.tab_3)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(60, 310, 221, 51))
        self.label_15.setFont(font4)
        self.label_15.setAlignment(Qt.AlignCenter)
        self.label_16 = QLabel(self.tab_3)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(20, 250, 311, 81))
        self.label_16.setFont(font3)
        self.label_16.setAlignment(Qt.AlignCenter)
        self.label_16.setWordWrap(True)
        self.label_18 = QLabel(self.tab_3)
        self.label_18.setObjectName(u"label_18")
        self.label_18.setGeometry(QRect(100, 20, 141, 16))
        self.label_18.setFont(font3)
        self.label_18.setAlignment(Qt.AlignCenter)
        self.frame_12 = QFrame(self.tab_3)
        self.frame_12.setObjectName(u"frame_12")
        self.frame_12.setGeometry(QRect(100, 40, 161, 211))
        self.frame_12.setContextMenuPolicy(Qt.NoContextMenu)
        self.frame_12.setFrameShape(QFrame.Box)
        self.frame_12.setFrameShadow(QFrame.Raised)
        self.frame_12.setLineWidth(2)
        self.label_46 = QLabel(self.frame_12)
        self.label_46.setObjectName(u"label_46")
        self.label_46.setGeometry(QRect(10, 10, 141, 191))
        self.label_46.setPixmap(QPixmap(u"../KuihRaya/cornflakes_crunchy.jpeg"))
        self.label_46.setScaledContents(True)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QWidget()
        self.tab_4.setObjectName(u"tab_4")
        self.label_17 = QLabel(self.tab_4)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setGeometry(QRect(60, 320, 221, 51))
        self.label_17.setFont(font4)
        self.label_17.setAlignment(Qt.AlignCenter)
        self.label_19 = QLabel(self.tab_4)
        self.label_19.setObjectName(u"label_19")
        self.label_19.setGeometry(QRect(20, 250, 311, 81))
        self.label_19.setFont(font3)
        self.label_19.setAlignment(Qt.AlignCenter)
        self.label_19.setWordWrap(True)
        self.frame_5 = QFrame(self.tab_4)
        self.frame_5.setObjectName(u"frame_5")
        self.frame_5.setGeometry(QRect(90, 40, 161, 211))
        self.frame_5.setContextMenuPolicy(Qt.NoContextMenu)
        self.frame_5.setFrameShape(QFrame.Box)
        self.frame_5.setFrameShadow(QFrame.Raised)
        self.frame_5.setLineWidth(2)
        self.label_20 = QLabel(self.frame_5)
        self.label_20.setObjectName(u"label_20")
        self.label_20.setGeometry(QRect(10, 10, 141, 191))
        self.label_20.setPixmap(QPixmap(u"../KuihRaya/dahlia.jpg"))
        self.label_20.setScaledContents(True)
        self.label_21 = QLabel(self.tab_4)
        self.label_21.setObjectName(u"label_21")
        self.label_21.setGeometry(QRect(100, 20, 141, 16))
        self.label_21.setFont(font3)
        self.label_21.setAlignment(Qt.AlignCenter)
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_5 = QWidget()
        self.tab_5.setObjectName(u"tab_5")
        self.label_22 = QLabel(self.tab_5)
        self.label_22.setObjectName(u"label_22")
        self.label_22.setGeometry(QRect(30, 220, 291, 81))
        self.label_22.setFont(font3)
        self.label_22.setAlignment(Qt.AlignCenter)
        self.label_22.setWordWrap(True)
        self.frame_6 = QFrame(self.tab_5)
        self.frame_6.setObjectName(u"frame_6")
        self.frame_6.setGeometry(QRect(90, 40, 171, 171))
        self.frame_6.setContextMenuPolicy(Qt.NoContextMenu)
        self.frame_6.setFrameShape(QFrame.Box)
        self.frame_6.setFrameShadow(QFrame.Raised)
        self.frame_6.setLineWidth(2)
        self.label_23 = QLabel(self.frame_6)
        self.label_23.setObjectName(u"label_23")
        self.label_23.setGeometry(QRect(10, 10, 151, 151))
        self.label_23.setPixmap(QPixmap(u"../KuihRaya/makmur.jpg"))
        self.label_23.setScaledContents(True)
        self.label_24 = QLabel(self.tab_5)
        self.label_24.setObjectName(u"label_24")
        self.label_24.setGeometry(QRect(60, 300, 221, 51))
        self.label_24.setFont(font4)
        self.label_24.setAlignment(Qt.AlignCenter)
        self.label_25 = QLabel(self.tab_5)
        self.label_25.setObjectName(u"label_25")
        self.label_25.setGeometry(QRect(100, 20, 141, 16))
        self.label_25.setFont(font3)
        self.label_25.setAlignment(Qt.AlignCenter)
        self.tabWidget.addTab(self.tab_5, "")
        self.tab_6 = QWidget()
        self.tab_6.setObjectName(u"tab_6")
        self.label_26 = QLabel(self.tab_6)
        self.label_26.setObjectName(u"label_26")
        self.label_26.setGeometry(QRect(20, 230, 301, 81))
        self.label_26.setFont(font3)
        self.label_26.setAlignment(Qt.AlignCenter)
        self.label_26.setWordWrap(True)
        self.label_27 = QLabel(self.tab_6)
        self.label_27.setObjectName(u"label_27")
        self.label_27.setGeometry(QRect(100, 20, 141, 16))
        self.label_27.setFont(font3)
        self.label_27.setAlignment(Qt.AlignCenter)
        self.frame_7 = QFrame(self.tab_6)
        self.frame_7.setObjectName(u"frame_7")
        self.frame_7.setGeometry(QRect(90, 40, 171, 171))
        self.frame_7.setContextMenuPolicy(Qt.NoContextMenu)
        self.frame_7.setFrameShape(QFrame.Box)
        self.frame_7.setFrameShadow(QFrame.Raised)
        self.frame_7.setLineWidth(2)
        self.label_28 = QLabel(self.frame_7)
        self.label_28.setObjectName(u"label_28")
        self.label_28.setGeometry(QRect(10, 10, 151, 151))
        self.label_28.setPixmap(QPixmap(u"../KuihRaya/rainbow.jpg"))
        self.label_28.setScaledContents(True)
        self.label_29 = QLabel(self.tab_6)
        self.label_29.setObjectName(u"label_29")
        self.label_29.setGeometry(QRect(60, 310, 221, 51))
        self.label_29.setFont(font4)
        self.label_29.setAlignment(Qt.AlignCenter)
        self.tabWidget.addTab(self.tab_6, "")
        self.tab_7 = QWidget()
        self.tab_7.setObjectName(u"tab_7")
        self.label_30 = QLabel(self.tab_7)
        self.label_30.setObjectName(u"label_30")
        self.label_30.setGeometry(QRect(20, 230, 311, 81))
        self.label_30.setFont(font3)
        self.label_30.setAlignment(Qt.AlignCenter)
        self.label_30.setWordWrap(True)
        self.label_31 = QLabel(self.tab_7)
        self.label_31.setObjectName(u"label_31")
        self.label_31.setGeometry(QRect(60, 310, 221, 51))
        self.label_31.setFont(font4)
        self.label_31.setAlignment(Qt.AlignCenter)
        self.label_32 = QLabel(self.tab_7)
        self.label_32.setObjectName(u"label_32")
        self.label_32.setGeometry(QRect(100, 20, 141, 16))
        self.label_32.setFont(font3)
        self.label_32.setAlignment(Qt.AlignCenter)
        self.frame_8 = QFrame(self.tab_7)
        self.frame_8.setObjectName(u"frame_8")
        self.frame_8.setGeometry(QRect(70, 50, 211, 151))
        self.frame_8.setContextMenuPolicy(Qt.NoContextMenu)
        self.frame_8.setFrameShape(QFrame.Box)
        self.frame_8.setFrameShadow(QFrame.Raised)
        self.frame_8.setLineWidth(2)
        self.label_33 = QLabel(self.frame_8)
        self.label_33.setObjectName(u"label_33")
        self.label_33.setGeometry(QRect(10, 10, 191, 131))
        self.label_33.setPixmap(QPixmap(u"../KuihRaya/red_pearl.png"))
        self.label_33.setScaledContents(True)
        self.tabWidget.addTab(self.tab_7, "")
        self.tab_8 = QWidget()
        self.tab_8.setObjectName(u"tab_8")
        self.label_37 = QLabel(self.tab_8)
        self.label_37.setObjectName(u"label_37")
        self.label_37.setGeometry(QRect(60, 310, 221, 51))
        self.label_37.setFont(font4)
        self.label_37.setAlignment(Qt.AlignCenter)
        self.label_34 = QLabel(self.tab_8)
        self.label_34.setObjectName(u"label_34")
        self.label_34.setGeometry(QRect(20, 220, 311, 81))
        self.label_34.setFont(font3)
        self.label_34.setAlignment(Qt.AlignCenter)
        self.label_34.setWordWrap(True)
        self.label_36 = QLabel(self.tab_8)
        self.label_36.setObjectName(u"label_36")
        self.label_36.setGeometry(QRect(100, 20, 141, 16))
        self.label_36.setFont(font3)
        self.label_36.setAlignment(Qt.AlignCenter)
        self.frame_9 = QFrame(self.tab_8)
        self.frame_9.setObjectName(u"frame_9")
        self.frame_9.setGeometry(QRect(70, 50, 211, 151))
        self.frame_9.setContextMenuPolicy(Qt.NoContextMenu)
        self.frame_9.setFrameShape(QFrame.Box)
        self.frame_9.setFrameShadow(QFrame.Raised)
        self.frame_9.setLineWidth(2)
        self.label_35 = QLabel(self.frame_9)
        self.label_35.setObjectName(u"label_35")
        self.label_35.setGeometry(QRect(10, 10, 191, 131))
        self.label_35.setPixmap(QPixmap(u"../KuihRaya/semperit.jpg"))
        self.label_35.setScaledContents(True)
        self.tabWidget.addTab(self.tab_8, "")
        self.tab_9 = QWidget()
        self.tab_9.setObjectName(u"tab_9")
        self.label_38 = QLabel(self.tab_9)
        self.label_38.setObjectName(u"label_38")
        self.label_38.setGeometry(QRect(70, 300, 221, 51))
        self.label_38.setFont(font4)
        self.label_38.setAlignment(Qt.AlignCenter)
        self.label_39 = QLabel(self.tab_9)
        self.label_39.setObjectName(u"label_39")
        self.label_39.setGeometry(QRect(20, 220, 311, 81))
        self.label_39.setFont(font3)
        self.label_39.setAlignment(Qt.AlignCenter)
        self.label_39.setWordWrap(True)
        self.label_40 = QLabel(self.tab_9)
        self.label_40.setObjectName(u"label_40")
        self.label_40.setGeometry(QRect(100, 20, 141, 16))
        self.label_40.setFont(font3)
        self.label_40.setAlignment(Qt.AlignCenter)
        self.frame_10 = QFrame(self.tab_9)
        self.frame_10.setObjectName(u"frame_10")
        self.frame_10.setGeometry(QRect(70, 50, 211, 151))
        self.frame_10.setContextMenuPolicy(Qt.NoContextMenu)
        self.frame_10.setFrameShape(QFrame.Box)
        self.frame_10.setFrameShadow(QFrame.Raised)
        self.frame_10.setLineWidth(2)
        self.label_41 = QLabel(self.frame_10)
        self.label_41.setObjectName(u"label_41")
        self.label_41.setGeometry(QRect(10, 10, 191, 131))
        self.label_41.setPixmap(QPixmap(u"../KuihRaya/suji.jpg"))
        self.label_41.setScaledContents(True)
        self.tabWidget.addTab(self.tab_9, "")
        self.tab_10 = QWidget()
        self.tab_10.setObjectName(u"tab_10")
        self.label_42 = QLabel(self.tab_10)
        self.label_42.setObjectName(u"label_42")
        self.label_42.setGeometry(QRect(100, 20, 141, 16))
        self.label_42.setFont(font3)
        self.label_42.setAlignment(Qt.AlignCenter)
        self.label_43 = QLabel(self.tab_10)
        self.label_43.setObjectName(u"label_43")
        self.label_43.setGeometry(QRect(20, 220, 311, 81))
        self.label_43.setFont(font3)
        self.label_43.setAlignment(Qt.AlignCenter)
        self.label_43.setWordWrap(True)
        self.frame_11 = QFrame(self.tab_10)
        self.frame_11.setObjectName(u"frame_11")
        self.frame_11.setGeometry(QRect(70, 50, 211, 151))
        self.frame_11.setContextMenuPolicy(Qt.NoContextMenu)
        self.frame_11.setFrameShape(QFrame.Box)
        self.frame_11.setFrameShadow(QFrame.Raised)
        self.frame_11.setLineWidth(2)
        self.label_44 = QLabel(self.frame_11)
        self.label_44.setObjectName(u"label_44")
        self.label_44.setGeometry(QRect(10, 10, 191, 131))
        self.label_44.setPixmap(QPixmap(u"../KuihRaya/tart_nenas.jpg"))
        self.label_44.setScaledContents(True)
        self.label_45 = QLabel(self.tab_10)
        self.label_45.setObjectName(u"label_45")
        self.label_45.setGeometry(QRect(70, 300, 221, 51))
        self.label_45.setFont(font4)
        self.label_45.setAlignment(Qt.AlignCenter)
        self.tabWidget.addTab(self.tab_10, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 400, 22))
        font5 = QFont()
        font5.setFamilies([u"Georgia"])
        font5.setPointSize(10)
        self.menubar.setFont(font5)
        self.menubar.setLayoutDirection(Qt.LeftToRight)
        self.menupreview_order = QMenu(self.menubar)
        self.menupreview_order.setObjectName(u"menupreview_order")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.menubar.addAction(self.menupreview_order.menuAction())
        self.menupreview_order.addAction(self.actionlist_kuih_raya)
        self.menupreview_order.addAction(self.actionnew_order)
        self.menupreview_order.addAction(self.actionupdate_order)
        self.menupreview_order.addAction(self.actionpreview_order)
        self.menupreview_order.addAction(self.actionpreview_stocks)

        self.retranslateUi(MainWindow)

        self.tabWidget.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.actionnew_customer.setText(QCoreApplication.translate("MainWindow", u"new customer", None))
        self.actionexisting_customer.setText(QCoreApplication.translate("MainWindow", u"existing customer", None))
        self.actionlist_kuih_raya.setText(QCoreApplication.translate("MainWindow", u"list kuih raya", None))
        self.actionnew_order.setText(QCoreApplication.translate("MainWindow", u"new order", None))
        self.actionupdate_order.setText(QCoreApplication.translate("MainWindow", u"update order", None))
        self.actionpreview_order.setText(QCoreApplication.translate("MainWindow", u"preview order", None))
        self.actionpreview_stocks.setText(QCoreApplication.translate("MainWindow", u"preview stocks", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"KameliaCookies", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"List Kuih Raya 2024", None))
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"Almond London", None))
        self.label_8.setText("")
        self.label_9.setText(QCoreApplication.translate("MainWindow", u"This cookie come in 3 parts. 1, the almond. 2, the crunchy biscuit that encases the almond then 3rd, the melted chocolate that pours over the biscuit, then often sprinkled with toasted nibs or sprinkles", None))
        self.label_10.setText(QCoreApplication.translate("MainWindow", u"RM39/45 pieces", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_1), QCoreApplication.translate("MainWindow", u"Almond London", None))
        self.label_11.setText(QCoreApplication.translate("MainWindow", u"RM40/20 pieces", None))
        self.label_12.setText(QCoreApplication.translate("MainWindow", u"A slightly crisp outer shell that holds up to some heat with an inner core that's soft and chewy.", None))
        self.label_13.setText(QCoreApplication.translate("MainWindow", u"Cookies", None))
        self.label_14.setText("")
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QCoreApplication.translate("MainWindow", u"Cookies", None))
        self.label_15.setText(QCoreApplication.translate("MainWindow", u"RM31/45 pieces", None))
        self.label_16.setText(QCoreApplication.translate("MainWindow", u"These butter-rich cookies are rolled with crunchy cornflakes so every bite is a perfect crunch. The cookie also melts in your mouth.", None))
        self.label_18.setText(QCoreApplication.translate("MainWindow", u"Cornflakes Crunchy", None))
        self.label_46.setText("")
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QCoreApplication.translate("MainWindow", u"Cornflakes Crunchy", None))
        self.label_17.setText(QCoreApplication.translate("MainWindow", u"RM33/45 pieces", None))
        self.label_19.setText(QCoreApplication.translate("MainWindow", u"Decorated with its signature kiwi and strawberry jelly on top, Dahlia Jelly cookies are butter cookies that melt immediately in your mouth, leaving you with a heavenly aftertaste.", None))
        self.label_20.setText("")
        self.label_21.setText(QCoreApplication.translate("MainWindow", u"Dahlia", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), QCoreApplication.translate("MainWindow", u"Dahlia", None))
        self.label_22.setText(QCoreApplication.translate("MainWindow", u"Melt-in-you-mouth pastry filled with a sweet peanut filling and dust with icing sugar", None))
        self.label_23.setText("")
        self.label_24.setText(QCoreApplication.translate("MainWindow", u"RM30/50 pieces", None))
        self.label_25.setText(QCoreApplication.translate("MainWindow", u"Makmur", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), QCoreApplication.translate("MainWindow", u"Makmur", None))
        self.label_26.setText(QCoreApplication.translate("MainWindow", u"The delicious base combines vanilla frosting with exotic coconut, while middle notes of passion fruit and buttercream add richness. Top notes of sweet orange and creamy peach add a fresh fruity finale.", None))
        self.label_27.setText(QCoreApplication.translate("MainWindow", u"Rainbow", None))
        self.label_28.setText("")
        self.label_29.setText(QCoreApplication.translate("MainWindow", u"RM35/50 pieces", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), QCoreApplication.translate("MainWindow", u"Rainbow", None))
        self.label_30.setText(QCoreApplication.translate("MainWindow", u"Very crunchy, very delectable\u2026  Buttery batter mixed with a variety of natural ingredients and cherries for colour.  Once you start, you can\u2019t stop kind of cookie", None))
        self.label_31.setText(QCoreApplication.translate("MainWindow", u"RM31/50 pieces", None))
        self.label_32.setText(QCoreApplication.translate("MainWindow", u"Red Pearl", None))
        self.label_33.setText("")
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_7), QCoreApplication.translate("MainWindow", u"Red Pearl", None))
        self.label_37.setText(QCoreApplication.translate("MainWindow", u"RM32/50 pieces", None))
        self.label_34.setText(QCoreApplication.translate("MainWindow", u"An airy and light version of a butter cookie, it's traditionally made with a mixture of egg yolks, corn flour and regular flour. This is the kind of cookie you can eat and keep eating, till the whole jar is gone and yet you'll want more.", None))
        self.label_36.setText(QCoreApplication.translate("MainWindow", u"Semperit", None))
        self.label_35.setText("")
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_8), QCoreApplication.translate("MainWindow", u"Semperit", None))
        self.label_38.setText(QCoreApplication.translate("MainWindow", u"RM30/50 pieces", None))
        self.label_39.setText(QCoreApplication.translate("MainWindow", u"Suji biscuit is a melt in your mouth cookie made from flour, ghee and sugar with a pinch of salt that kind of gives the balance between sweet and salty.", None))
        self.label_40.setText(QCoreApplication.translate("MainWindow", u"Suji", None))
        self.label_41.setText("")
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_9), QCoreApplication.translate("MainWindow", u"Suji", None))
        self.label_42.setText(QCoreApplication.translate("MainWindow", u"Tart Nenas", None))
        self.label_43.setText(QCoreApplication.translate("MainWindow", u"a small, bite-size tart filled or topped with pineapple jam that almost crumbly yet buttery on the outside; sweet, tart and almost chewy in its filling", None))
        self.label_44.setText("")
        self.label_45.setText(QCoreApplication.translate("MainWindow", u"RM35/50 pieces", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_10), QCoreApplication.translate("MainWindow", u"Tart Nenas", None))
        self.menupreview_order.setTitle(QCoreApplication.translate("MainWindow", u"cookies!", None))
    # retranslateUi

