# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'new_customer.ui'
##
## Created by: Qt User Interface Compiler version 6.6.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QComboBox, QFormLayout, QGroupBox,
    QHBoxLayout, QLabel, QLineEdit, QMainWindow,
    QMenu, QMenuBar, QPushButton, QScrollArea,
    QSizePolicy, QSpinBox, QStatusBar, QWidget)
#import image_rc

class Ui_NewOrderW2(object):
    def setupUi(self, NewOrderW2):
        if not NewOrderW2.objectName():
            NewOrderW2.setObjectName(u"NewOrderW2")
        NewOrderW2.resize(400, 551)
        self.actionnew_customer = QAction(NewOrderW2)
        self.actionnew_customer.setObjectName(u"actionnew_customer")
        self.actionnew_customer.setCheckable(False)
        self.actionnew_customer.setChecked(False)
        self.actionnew_customer.setShortcutContext(Qt.ApplicationShortcut)
        self.actionnew_customer.setAutoRepeat(False)
        self.actionnew_customer.setMenuRole(QAction.ApplicationSpecificRole)
        self.actionnew_customer.setShortcutVisibleInContextMenu(False)
        self.actionexisting_customer = QAction(NewOrderW2)
        self.actionexisting_customer.setObjectName(u"actionexisting_customer")
        self.actionlist_kuih_raya = QAction(NewOrderW2)
        self.actionlist_kuih_raya.setObjectName(u"actionlist_kuih_raya")
        self.actionnew_order = QAction(NewOrderW2)
        self.actionnew_order.setObjectName(u"actionnew_order")
        self.actionupdate_order = QAction(NewOrderW2)
        self.actionupdate_order.setObjectName(u"actionupdate_order")
        self.actionpreview_order = QAction(NewOrderW2)
        self.actionpreview_order.setObjectName(u"actionpreview_order")
        self.actionpreview_stocks = QAction(NewOrderW2)
        self.actionpreview_stocks.setObjectName(u"actionpreview_stocks")
        self.centralwidget = QWidget(NewOrderW2)
        self.centralwidget.setObjectName(u"centralwidget")
        self.label = QLabel(self.centralwidget)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(120, 10, 161, 51))
        font = QFont()
        font.setFamilies([u"Lucida Handwriting"])
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setAlignment(Qt.AlignCenter)
        self.label.setWordWrap(False)
        self.groupBox = QGroupBox(self.centralwidget)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(20, 60, 361, 451))
        font1 = QFont()
        font1.setFamilies([u"Georgia"])
        self.groupBox.setFont(font1)
        self.formLayoutWidget = QWidget(self.groupBox)
        self.formLayoutWidget.setObjectName(u"formLayoutWidget")
        self.formLayoutWidget.setGeometry(QRect(20, 30, 321, 61))
        self.formLayout = QFormLayout(self.formLayoutWidget)
        self.formLayout.setObjectName(u"formLayout")
        self.formLayout.setLabelAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.CustomerNameInputW2 = QLineEdit(self.formLayoutWidget)
        self.CustomerNameInputW2.setObjectName(u"CustomerNameInputW2")

        self.formLayout.setWidget(0, QFormLayout.FieldRole, self.CustomerNameInputW2)

        self.NoPhoneLabel = QLabel(self.formLayoutWidget)
        self.NoPhoneLabel.setObjectName(u"NoPhoneLabel")
        self.NoPhoneLabel.setFont(font1)
        self.NoPhoneLabel.setAlignment(Qt.AlignCenter)

        self.formLayout.setWidget(1, QFormLayout.LabelRole, self.NoPhoneLabel)

        self.PhoneInput = QLineEdit(self.formLayoutWidget)
        self.PhoneInput.setObjectName(u"PhoneInput")

        self.formLayout.setWidget(1, QFormLayout.FieldRole, self.PhoneInput)

        self.CustomerNameLabel = QLabel(self.formLayoutWidget)
        self.CustomerNameLabel.setObjectName(u"CustomerNameLabel")
        self.CustomerNameLabel.setFont(font1)
        self.CustomerNameLabel.setLayoutDirection(Qt.LeftToRight)
        self.CustomerNameLabel.setAlignment(Qt.AlignCenter)

        self.formLayout.setWidget(0, QFormLayout.LabelRole, self.CustomerNameLabel)

        self.scrollArea = QScrollArea(self.groupBox)
        self.scrollArea.setObjectName(u"scrollArea")
        self.scrollArea.setGeometry(QRect(20, 90, 321, 261))
        self.scrollArea.setWidgetResizable(True)
        self.scrollAreaWidgetContents = QWidget()
        self.scrollAreaWidgetContents.setObjectName(u"scrollAreaWidgetContents")
        self.scrollAreaWidgetContents.setGeometry(QRect(0, 0, 319, 259))
        self.horizontalLayoutWidget = QWidget(self.scrollAreaWidgetContents)
        self.horizontalLayoutWidget.setObjectName(u"horizontalLayoutWidget")
        self.horizontalLayoutWidget.setGeometry(QRect(20, 40, 281, 41))
        self.horizontalLayout = QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.W2Kuih01 = QComboBox(self.horizontalLayoutWidget)
        self.W2Kuih01.addItem("")
        self.W2Kuih01.addItem("")
        self.W2Kuih01.addItem("")
        self.W2Kuih01.addItem("")
        self.W2Kuih01.addItem("")
        self.W2Kuih01.addItem("")
        self.W2Kuih01.addItem("")
        self.W2Kuih01.addItem("")
        self.W2Kuih01.addItem("")
        self.W2Kuih01.addItem("")
        self.W2Kuih01.addItem("")
        self.W2Kuih01.setObjectName(u"W2Kuih01")

        self.horizontalLayout.addWidget(self.W2Kuih01)

        self.w2Qkuih01 = QSpinBox(self.horizontalLayoutWidget)
        self.w2Qkuih01.setObjectName(u"w2Qkuih01")
        self.w2Qkuih01.setContextMenuPolicy(Qt.NoContextMenu)
        self.w2Qkuih01.setAlignment(Qt.AlignCenter)
        self.w2Qkuih01.setMaximum(200)

        self.horizontalLayout.addWidget(self.w2Qkuih01)

        self.horizontalLayoutWidget_2 = QWidget(self.scrollAreaWidgetContents)
        self.horizontalLayoutWidget_2.setObjectName(u"horizontalLayoutWidget_2")
        self.horizontalLayoutWidget_2.setGeometry(QRect(20, 10, 281, 31))
        self.horizontalLayout_2 = QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setObjectName(u"horizontalLayout_2")
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.label_2 = QLabel(self.horizontalLayoutWidget_2)
        self.label_2.setObjectName(u"label_2")

        self.horizontalLayout_2.addWidget(self.label_2)

        self.label_3 = QLabel(self.horizontalLayoutWidget_2)
        self.label_3.setObjectName(u"label_3")

        self.horizontalLayout_2.addWidget(self.label_3)

        self.horizontalLayoutWidget_3 = QWidget(self.scrollAreaWidgetContents)
        self.horizontalLayoutWidget_3.setObjectName(u"horizontalLayoutWidget_3")
        self.horizontalLayoutWidget_3.setGeometry(QRect(20, 120, 281, 41))
        self.horizontalLayout_3 = QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setObjectName(u"horizontalLayout_3")
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.W2Kuih03 = QComboBox(self.horizontalLayoutWidget_3)
        self.W2Kuih03.addItem("")
        self.W2Kuih03.addItem("")
        self.W2Kuih03.addItem("")
        self.W2Kuih03.addItem("")
        self.W2Kuih03.addItem("")
        self.W2Kuih03.addItem("")
        self.W2Kuih03.addItem("")
        self.W2Kuih03.addItem("")
        self.W2Kuih03.addItem("")
        self.W2Kuih03.addItem("")
        self.W2Kuih03.addItem("")
        self.W2Kuih03.setObjectName(u"W2Kuih03")

        self.horizontalLayout_3.addWidget(self.W2Kuih03)

        self.w2Qkuih03 = QSpinBox(self.horizontalLayoutWidget_3)
        self.w2Qkuih03.setObjectName(u"w2Qkuih03")
        self.w2Qkuih03.setAlignment(Qt.AlignCenter)
        self.w2Qkuih03.setMaximum(200)

        self.horizontalLayout_3.addWidget(self.w2Qkuih03)

        self.horizontalLayoutWidget_4 = QWidget(self.scrollAreaWidgetContents)
        self.horizontalLayoutWidget_4.setObjectName(u"horizontalLayoutWidget_4")
        self.horizontalLayoutWidget_4.setGeometry(QRect(20, 80, 281, 41))
        self.horizontalLayout_4 = QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_4.setObjectName(u"horizontalLayout_4")
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.W2Kuih02 = QComboBox(self.horizontalLayoutWidget_4)
        self.W2Kuih02.addItem("")
        self.W2Kuih02.addItem("")
        self.W2Kuih02.addItem("")
        self.W2Kuih02.addItem("")
        self.W2Kuih02.addItem("")
        self.W2Kuih02.addItem("")
        self.W2Kuih02.addItem("")
        self.W2Kuih02.addItem("")
        self.W2Kuih02.addItem("")
        self.W2Kuih02.addItem("")
        self.W2Kuih02.addItem("")
        self.W2Kuih02.setObjectName(u"W2Kuih02")

        self.horizontalLayout_4.addWidget(self.W2Kuih02)

        self.w2Qkuih02 = QSpinBox(self.horizontalLayoutWidget_4)
        self.w2Qkuih02.setObjectName(u"w2Qkuih02")
        self.w2Qkuih02.setAlignment(Qt.AlignCenter)
        self.w2Qkuih02.setMaximum(200)

        self.horizontalLayout_4.addWidget(self.w2Qkuih02)

        self.horizontalLayoutWidget_5 = QWidget(self.scrollAreaWidgetContents)
        self.horizontalLayoutWidget_5.setObjectName(u"horizontalLayoutWidget_5")
        self.horizontalLayoutWidget_5.setGeometry(QRect(20, 160, 281, 41))
        self.horizontalLayout_5 = QHBoxLayout(self.horizontalLayoutWidget_5)
        self.horizontalLayout_5.setObjectName(u"horizontalLayout_5")
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.W2Kuih04 = QComboBox(self.horizontalLayoutWidget_5)
        self.W2Kuih04.addItem("")
        self.W2Kuih04.addItem("")
        self.W2Kuih04.addItem("")
        self.W2Kuih04.addItem("")
        self.W2Kuih04.addItem("")
        self.W2Kuih04.addItem("")
        self.W2Kuih04.addItem("")
        self.W2Kuih04.addItem("")
        self.W2Kuih04.addItem("")
        self.W2Kuih04.addItem("")
        self.W2Kuih04.addItem("")
        self.W2Kuih04.setObjectName(u"W2Kuih04")

        self.horizontalLayout_5.addWidget(self.W2Kuih04)

        self.w2Qkuih04 = QSpinBox(self.horizontalLayoutWidget_5)
        self.w2Qkuih04.setObjectName(u"w2Qkuih04")
        self.w2Qkuih04.setAlignment(Qt.AlignCenter)
        self.w2Qkuih04.setMaximum(200)

        self.horizontalLayout_5.addWidget(self.w2Qkuih04)

        self.horizontalLayoutWidget_7 = QWidget(self.scrollAreaWidgetContents)
        self.horizontalLayoutWidget_7.setObjectName(u"horizontalLayoutWidget_7")
        self.horizontalLayoutWidget_7.setGeometry(QRect(20, 200, 281, 41))
        self.horizontalLayout_7 = QHBoxLayout(self.horizontalLayoutWidget_7)
        self.horizontalLayout_7.setObjectName(u"horizontalLayout_7")
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.W2Kuih05 = QComboBox(self.horizontalLayoutWidget_7)
        self.W2Kuih05.addItem("")
        self.W2Kuih05.addItem("")
        self.W2Kuih05.addItem("")
        self.W2Kuih05.addItem("")
        self.W2Kuih05.addItem("")
        self.W2Kuih05.addItem("")
        self.W2Kuih05.addItem("")
        self.W2Kuih05.addItem("")
        self.W2Kuih05.addItem("")
        self.W2Kuih05.addItem("")
        self.W2Kuih05.addItem("")
        self.W2Kuih05.setObjectName(u"W2Kuih05")

        self.horizontalLayout_7.addWidget(self.W2Kuih05)

        self.w2Qkuih05 = QSpinBox(self.horizontalLayoutWidget_7)
        self.w2Qkuih05.setObjectName(u"w2Qkuih05")
        self.w2Qkuih05.setAlignment(Qt.AlignCenter)
        self.w2Qkuih05.setMaximum(200)

        self.horizontalLayout_7.addWidget(self.w2Qkuih05)

        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.horizontalLayoutWidget_6 = QWidget(self.groupBox)
        self.horizontalLayoutWidget_6.setObjectName(u"horizontalLayoutWidget_6")
        self.horizontalLayoutWidget_6.setGeometry(QRect(130, 360, 211, 21))
        self.horizontalLayout_6 = QHBoxLayout(self.horizontalLayoutWidget_6)
        self.horizontalLayout_6.setObjectName(u"horizontalLayout_6")
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.label_5 = QLabel(self.horizontalLayoutWidget_6)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setAlignment(Qt.AlignCenter)

        self.horizontalLayout_6.addWidget(self.label_5)

        self.TotalW2 = QLabel(self.horizontalLayoutWidget_6)
        self.TotalW2.setObjectName(u"TotalW2")
        self.TotalW2.setAlignment(Qt.AlignCenter)

        self.horizontalLayout_6.addWidget(self.TotalW2)

        self.horizontalLayoutWidget_9 = QWidget(self.groupBox)
        self.horizontalLayoutWidget_9.setObjectName(u"horizontalLayoutWidget_9")
        self.horizontalLayoutWidget_9.setGeometry(QRect(130, 400, 211, 21))
        self.horizontalLayout_9 = QHBoxLayout(self.horizontalLayoutWidget_9)
        self.horizontalLayout_9.setObjectName(u"horizontalLayout_9")
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.label_8 = QLabel(self.horizontalLayoutWidget_9)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setAlignment(Qt.AlignCenter)

        self.horizontalLayout_9.addWidget(self.label_8)

        self.BalanceW2 = QLabel(self.horizontalLayoutWidget_9)
        self.BalanceW2.setObjectName(u"BalanceW2")
        self.BalanceW2.setAlignment(Qt.AlignCenter)

        self.horizontalLayout_9.addWidget(self.BalanceW2)

        self.horizontalLayoutWidget_10 = QWidget(self.groupBox)
        self.horizontalLayoutWidget_10.setObjectName(u"horizontalLayoutWidget_10")
        self.horizontalLayoutWidget_10.setGeometry(QRect(130, 380, 211, 22))
        self.horizontalLayout_10 = QHBoxLayout(self.horizontalLayoutWidget_10)
        self.horizontalLayout_10.setObjectName(u"horizontalLayout_10")
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.label_6 = QLabel(self.horizontalLayoutWidget_10)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setAlignment(Qt.AlignCenter)

        self.horizontalLayout_10.addWidget(self.label_6)

        self.DepositW2 = QLineEdit(self.horizontalLayoutWidget_10)
        self.DepositW2.setObjectName(u"DepositW2")
        self.DepositW2.setMaxLength(32750)
        self.DepositW2.setAlignment(Qt.AlignCenter)

        self.horizontalLayout_10.addWidget(self.DepositW2)

        self.horizontalLayoutWidget_8 = QWidget(self.groupBox)
        self.horizontalLayoutWidget_8.setObjectName(u"horizontalLayoutWidget_8")
        self.horizontalLayoutWidget_8.setGeometry(QRect(160, 420, 181, 25))
        self.horizontalLayout_8 = QHBoxLayout(self.horizontalLayoutWidget_8)
        self.horizontalLayout_8.setObjectName(u"horizontalLayout_8")
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.AddNewOrderButton = QPushButton(self.horizontalLayoutWidget_8)
        self.AddNewOrderButton.setObjectName(u"AddNewOrderButton")

        self.horizontalLayout_8.addWidget(self.AddNewOrderButton)

        NewOrderW2.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(NewOrderW2)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 400, 22))
        font2 = QFont()
        font2.setFamilies([u"Georgia"])
        font2.setPointSize(10)
        self.menubar.setFont(font2)
        self.menubar.setLayoutDirection(Qt.LeftToRight)
        self.menulist_kuih_raya = QMenu(self.menubar)
        self.menulist_kuih_raya.setObjectName(u"menulist_kuih_raya")
        NewOrderW2.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(NewOrderW2)
        self.statusbar.setObjectName(u"statusbar")
        NewOrderW2.setStatusBar(self.statusbar)

        self.menubar.addAction(self.menulist_kuih_raya.menuAction())
        self.menulist_kuih_raya.addAction(self.actionlist_kuih_raya)
        self.menulist_kuih_raya.addAction(self.actionnew_order)
        self.menulist_kuih_raya.addAction(self.actionupdate_order)
        self.menulist_kuih_raya.addAction(self.actionpreview_order)
        self.menulist_kuih_raya.addAction(self.actionpreview_stocks)

        self.retranslateUi(NewOrderW2)

        QMetaObject.connectSlotsByName(NewOrderW2)
    # setupUi

    def retranslateUi(self, NewOrderW2):
        NewOrderW2.setWindowTitle(QCoreApplication.translate("NewOrderW2", u"MainWindow", None))
        self.actionnew_customer.setText(QCoreApplication.translate("NewOrderW2", u"new customer", None))
        self.actionexisting_customer.setText(QCoreApplication.translate("NewOrderW2", u"existing customer", None))
        self.actionlist_kuih_raya.setText(QCoreApplication.translate("NewOrderW2", u"list kuih raya", None))
        self.actionnew_order.setText(QCoreApplication.translate("NewOrderW2", u"new order", None))
        self.actionupdate_order.setText(QCoreApplication.translate("NewOrderW2", u"update order", None))
        self.actionpreview_order.setText(QCoreApplication.translate("NewOrderW2", u"preview order", None))
        self.actionpreview_stocks.setText(QCoreApplication.translate("NewOrderW2", u"preview stocks", None))
        self.label.setText(QCoreApplication.translate("NewOrderW2", u"KameliaCookies", None))
        self.groupBox.setTitle(QCoreApplication.translate("NewOrderW2", u"New Customer", None))
        self.NoPhoneLabel.setText(QCoreApplication.translate("NewOrderW2", u"Phone Number :", None))
        self.CustomerNameLabel.setText(QCoreApplication.translate("NewOrderW2", u"Name :", None))
        self.W2Kuih01.setItemText(0, QCoreApplication.translate("NewOrderW2", u"None", None))
        self.W2Kuih01.setItemText(1, QCoreApplication.translate("NewOrderW2", u"Almond_London", None))
        self.W2Kuih01.setItemText(2, QCoreApplication.translate("NewOrderW2", u"Cookies", None))
        self.W2Kuih01.setItemText(3, QCoreApplication.translate("NewOrderW2", u"Cornflakes_Crunchy", None))
        self.W2Kuih01.setItemText(4, QCoreApplication.translate("NewOrderW2", u"Dahlia", None))
        self.W2Kuih01.setItemText(5, QCoreApplication.translate("NewOrderW2", u"Makmur", None))
        self.W2Kuih01.setItemText(6, QCoreApplication.translate("NewOrderW2", u"Rainbow", None))
        self.W2Kuih01.setItemText(7, QCoreApplication.translate("NewOrderW2", u"Red_Pearl", None))
        self.W2Kuih01.setItemText(8, QCoreApplication.translate("NewOrderW2", u"Semperit", None))
        self.W2Kuih01.setItemText(9, QCoreApplication.translate("NewOrderW2", u"Suji", None))
        self.W2Kuih01.setItemText(10, QCoreApplication.translate("NewOrderW2", u"Tart_Nenas", None))

        self.label_2.setText(QCoreApplication.translate("NewOrderW2", u"Kuih :", None))
        self.label_3.setText(QCoreApplication.translate("NewOrderW2", u"Quantity :", None))
        self.W2Kuih03.setItemText(0, QCoreApplication.translate("NewOrderW2", u"None", None))
        self.W2Kuih03.setItemText(1, QCoreApplication.translate("NewOrderW2", u"Almond_London", None))
        self.W2Kuih03.setItemText(2, QCoreApplication.translate("NewOrderW2", u"Cookies", None))
        self.W2Kuih03.setItemText(3, QCoreApplication.translate("NewOrderW2", u"Cornflakes_Crunchy", None))
        self.W2Kuih03.setItemText(4, QCoreApplication.translate("NewOrderW2", u"Dahlia", None))
        self.W2Kuih03.setItemText(5, QCoreApplication.translate("NewOrderW2", u"Makmur", None))
        self.W2Kuih03.setItemText(6, QCoreApplication.translate("NewOrderW2", u"Rainbow", None))
        self.W2Kuih03.setItemText(7, QCoreApplication.translate("NewOrderW2", u"Red_Pearl", None))
        self.W2Kuih03.setItemText(8, QCoreApplication.translate("NewOrderW2", u"Semperit", None))
        self.W2Kuih03.setItemText(9, QCoreApplication.translate("NewOrderW2", u"Suji", None))
        self.W2Kuih03.setItemText(10, QCoreApplication.translate("NewOrderW2", u"Tart_Nenas", None))

        self.W2Kuih02.setItemText(0, QCoreApplication.translate("NewOrderW2", u"None", None))
        self.W2Kuih02.setItemText(1, QCoreApplication.translate("NewOrderW2", u"Almond_London", None))
        self.W2Kuih02.setItemText(2, QCoreApplication.translate("NewOrderW2", u"Cookies", None))
        self.W2Kuih02.setItemText(3, QCoreApplication.translate("NewOrderW2", u"Cornflakes_Crunchy", None))
        self.W2Kuih02.setItemText(4, QCoreApplication.translate("NewOrderW2", u"Dahlia", None))
        self.W2Kuih02.setItemText(5, QCoreApplication.translate("NewOrderW2", u"Makmur", None))
        self.W2Kuih02.setItemText(6, QCoreApplication.translate("NewOrderW2", u"Rainbow", None))
        self.W2Kuih02.setItemText(7, QCoreApplication.translate("NewOrderW2", u"Red_Pearl", None))
        self.W2Kuih02.setItemText(8, QCoreApplication.translate("NewOrderW2", u"Semperit", None))
        self.W2Kuih02.setItemText(9, QCoreApplication.translate("NewOrderW2", u"Suji", None))
        self.W2Kuih02.setItemText(10, QCoreApplication.translate("NewOrderW2", u"Tart_Nenas", None))

        self.W2Kuih04.setItemText(0, QCoreApplication.translate("NewOrderW2", u"None", None))
        self.W2Kuih04.setItemText(1, QCoreApplication.translate("NewOrderW2", u"Almond_London", None))
        self.W2Kuih04.setItemText(2, QCoreApplication.translate("NewOrderW2", u"Cookies", None))
        self.W2Kuih04.setItemText(3, QCoreApplication.translate("NewOrderW2", u"Cornflakes_Crunchy", None))
        self.W2Kuih04.setItemText(4, QCoreApplication.translate("NewOrderW2", u"Dahlia", None))
        self.W2Kuih04.setItemText(5, QCoreApplication.translate("NewOrderW2", u"Makmur", None))
        self.W2Kuih04.setItemText(6, QCoreApplication.translate("NewOrderW2", u"Rainbow", None))
        self.W2Kuih04.setItemText(7, QCoreApplication.translate("NewOrderW2", u"Red_Pearl", None))
        self.W2Kuih04.setItemText(8, QCoreApplication.translate("NewOrderW2", u"Semperit", None))
        self.W2Kuih04.setItemText(9, QCoreApplication.translate("NewOrderW2", u"Suji", None))
        self.W2Kuih04.setItemText(10, QCoreApplication.translate("NewOrderW2", u"Tart_Nenas", None))

        self.W2Kuih05.setItemText(0, QCoreApplication.translate("NewOrderW2", u"None", None))
        self.W2Kuih05.setItemText(1, QCoreApplication.translate("NewOrderW2", u"Almond_London", None))
        self.W2Kuih05.setItemText(2, QCoreApplication.translate("NewOrderW2", u"Cookies", None))
        self.W2Kuih05.setItemText(3, QCoreApplication.translate("NewOrderW2", u"Cornflakes_Crunchy", None))
        self.W2Kuih05.setItemText(4, QCoreApplication.translate("NewOrderW2", u"Dahlia", None))
        self.W2Kuih05.setItemText(5, QCoreApplication.translate("NewOrderW2", u"Makmur", None))
        self.W2Kuih05.setItemText(6, QCoreApplication.translate("NewOrderW2", u"Rainbow", None))
        self.W2Kuih05.setItemText(7, QCoreApplication.translate("NewOrderW2", u"Red_Pearl", None))
        self.W2Kuih05.setItemText(8, QCoreApplication.translate("NewOrderW2", u"Semperit", None))
        self.W2Kuih05.setItemText(9, QCoreApplication.translate("NewOrderW2", u"Suji", None))
        self.W2Kuih05.setItemText(10, QCoreApplication.translate("NewOrderW2", u"Tart_Nenas", None))

        self.label_5.setText(QCoreApplication.translate("NewOrderW2", u"        Total :", None))
        self.TotalW2.setText(QCoreApplication.translate("NewOrderW2", u"RM?", None))
        self.label_8.setText(QCoreApplication.translate("NewOrderW2", u"   Balance :", None))
        self.BalanceW2.setText(QCoreApplication.translate("NewOrderW2", u"RM?", None))
        self.label_6.setText(QCoreApplication.translate("NewOrderW2", u"           Deposit :", None))
        self.DepositW2.setText("")
        self.AddNewOrderButton.setText(QCoreApplication.translate("NewOrderW2", u"+ Add Order", None))
        self.menulist_kuih_raya.setTitle(QCoreApplication.translate("NewOrderW2", u"cookies!", None))
    # retranslateUi

